### ISSUE TITLE
很多图片无法识别

### ISSUE THREAD

**Issue by chelongfei** [luyongfugx/hcSpriteCuter#3]
很荣幸能发现这么好的工具，但是实际操作中遇到了一些问题，有些图片无法切图,终端输出

enter while :0  200001
offPoint :87 0

对于矩阵判断这里不是很懂，应该是这里出了问题吧，希望您能抽出时间查看下这个问题，不胜感激！
附图片地址: http://isaac.icecat.cc/image/ap-trinkets.png

**Comment by luyongfugx** [comment]
@chelongfei  矩形这里必须有透明边，你给的这张图，貌似上下边没有透明，你尝试一下上下补给透明边试试，未经验证

**Comment by chelongfei** [comment]
可以的，非常感谢大神！已粉，非常感谢

**Comment by luyongfugx** [comment]
@chelongfei  客气
